kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-application
  template:
    metadata:
      name: spring-application
      labels:
        app: spring-application
    spec:
      containers:
        - name: spring-container
          image: rohitwasnik1112/spring:replaceImageTag
          ports:
            - containerPort: 8080
